envname: HuskyNavigateEnv
model_id: space3 #house13
target_orn: [0, 0, 1.57]
target_pos: [-14.3, 45.07, 0.5]
initial_orn: [0, 0, 4.71] #in radian
initial_pos: [3, 10, 1.2]
fov: 1.57
is_discrete: true

use_filler: true
display_ui: true
show_diagnostics: false
# ui_num: 3
ui_num: 2
# ui_components: [RGB_FILLED, DEPTH , SEMANTICS]
ui_components: [RGB_FILLED, DEPTH ]
random:
  random_initial_pose : false
  random_target_pose : false
  random_init_x_range: [-0.1, 0.1]
  random_init_y_range: [-0.1, 0.1]
  random_init_z_range: [-0.1, 0.1]
  random_init_rot_range: [-0.1, 0.1]

# output: [nonviz_sensor, rgb_filled, depth, semantics]
output: [nonviz_sensor, rgb_filled, depth]
resolution: 256

speed:
  timestep: 0.001
  frameskip: 10

mode: gui #gui|headless
verbose: false
# semantic_source: 2 # Matterport 3D
# semantic_color: 1 # Randoms
