# envname: DroneNavigateEnv
# model_id: area3
# target_orn: [0, 0, 1.57]
# target_pos: [-14.3, 45.07, 0.5]
# initial_orn: [0, 0, 4.71]
# initial_pos: [-14.3, 5, 1.2]

# fov: 1.57
# is_discrete: true

# use_filler: true
# display_ui: true
# show_diagnostics: false
# ui_num: 2
# # ui_components: [RGB_FILLED, DEPTH,SEMANTICS]
# ui_components: [DEPTH,SEMANTICS]
# # ui_components: [RGB_FILLED, DEPTH]
# random:
#   random_initial_pose : true
#   random_target_pose : false
#   random_init_x_range: [-0.1, 0.1]
#   random_init_y_range: [-0.1, 0.1]
#   random_init_z_range: [-0.1, 0.1]
#   random_init_rot_range: [-0.1, 0.1]

# # output: [nonviz_sensor, rgb_filled, depth, semantics]
# output: [nonviz_sensor, depth, semantics]
# # output: [nonviz_sensor, rgb_filled, depth]
# resolution: 256

# speed:
#   timestep: 0.01
#   frameskip: 1

# mode: gui #gui|headless
# verbose: false
# semantic_source: 1 # Matterport 3D
# #semantic_color: 1  # Randoms
# semantic_color: 1  #label index rgb code
envname: DroneNavigateEnv
model_id: space6
target_orn: [0, 0, 1.57]
target_pos: [0,0,1]
initial_orn: [0, 0, 1.37]
initial_pos: [0,0,1]
fov: 1.57
is_discrete: true

use_filler: true
display_ui: true
show_diagnostics: true
ui_num: 2
ui_components: [RGB_FILLED, DEPTH]
random:
  random_initial_pose : true
  random_target_pose : true
  random_init_x_range: [-0.1, 0.1]
  random_init_y_range: [-0.1, 0.1]
  random_init_z_range: [-0.1, 0.1]
  random_init_rot_range: [-0.1, 0.1]
  random_target_range: 0.1

output: [nonviz_sensor, rgb_filled, depth]
#output: [nonviz_sensor]
resolution: 256

speed:
  timestep: 0.01
  frameskip: 5

mode: gui #gui|headless
verbose: false
# semantic_source: 2 # Matterport 3D
# semantic_color: 1 # Randoms
